### ISSUE TITLE
Move repo to Jazzband?

### ISSUE THREAD

**Issue by claudep** [jazzband/django-tinymce#292]
Hi @aljosa, @Natim,

What would be your opinion on moving this repository to Jazzband (jazzband.co/)? I don't mean to hurt you, but maintainership is a bit minimal currently, so it might help to revitalize this package.

**Comment by Natim** [comment]
Hello @claudep 

Thank you for asking the question. I was also looking forward to add django-downloadview to JazzBand. I also think it might benefit the library to do so.

The problem is maintaining a library when one is not actively using it anymore.

Regarding jazzband, I think we need to improve the tests, it is currently too easy to break the lib. If you have any ideas I am interested.

**Comment by aljosa** [comment]
@claudep yes, @Natim suggested it before but just didn't have time to move forward with the idea.
What do we need to do?

**Comment by claudep** [comment]
Here you can find instructions: https://jazzband.co/about/guidelines
Transferring the repo to Jazzband on Github seems the first step to do.

**Comment by claudep** [comment]
> Regarding jazzband, I think we need to improve the tests, it is currently too easy to break the lib. If you have any ideas I am interested.

You mean JS tests? Django is using QUnit (https://qunitjs.com/) to test its JS code, maybe a hint…

**Comment by Natim** [comment]
> Transferring the repo to Jazzband on Github seems the first step to do.

@aljosa if you agree let's do that :)

**Comment by aljosa** [comment]
@Natim I've just asked on irc if it's ok to transfer the repo and work on issues/details like tests later

**Comment by aljosa** [comment]
@Natim after reading more on the website it looks to me it's ok to transfer so I did

**Comment by claudep** [comment]
:heart_eyes:
