### ISSUE TITLE
set callback functions 

### ISSUE THREAD

**Issue by esseti** [jazzband/django-tinymce#452]
How is it possible to create some settings in oreder that the tinymce.init is as the following?

```
tinymce.init({
  init_instance_callback: function (editor) {
    editor.on('blur', function (e) {
      console.log('Editor was blurred!');
    });
  }
});

```

I tried with

```
TINYMCE_DEFAULT_CONFIG = {
....
    "init_instance_callback":"""function (editor) {
editor.on('blur', function (e) {
    tinyMCE.triggerSave();
    console.log('test')
});"""

```

but that is then a string, not a valid funciton and it's not triggered.

My scope is to trigger an action when onblur, since using tinymce the event on input, that is: `$(':input').on('change', function () ..` is not triggered..

**Comment by Pantzan** [comment]
It looks like the `init_instance_callback` callback [is not supported](https://github.com/jazzband/django-tinymce/blob/master/tinymce/static/django_tinymce/init_tinymce.js#L10). Use the `setup` callback instead

**Comment by esseti** [comment]
do you have a working example for this case?

**Comment by Pantzan** [comment]
TINYMCE_DEFAULT_CONFIG = {
....
`"setup":"""function (editor) {
        editor.on('blur', function (e) {
        editor.save();
        console.log('test')
    });} """
}

The `blur` event in order to trigger the focus must be shifted to another input. In my projects clicking anywhere in the page does not trigger the event. As for the `save`, I am not using it  in my projects so I cannot test that functionality but I don't see any reason the `editor.save()` not to work.

If the issue is solved, please mark this ticket as closed.
